### ISSUE TITLE
Quarterly shifted KPI/report data

### ISSUE THREAD

**Issue by ember91** [Borsdata-Sweden/API#13]
Hi!

So I've got an issue with quarterly historical KPI/report data. For some instruments, such as instrument 8, output seems to be shifted a number of quarters. 

Try for example `/v1/instruments/8/kpis/quarter/summary`. The output is also attached here. Look at KPI 5. It has values for year 2021 and period (quarter) 4. That's the future! Now look at the corresponding report start date for instrument 8 (with another API call). It has data for year 2021 and period 4, but its report start date is for period 4 2021-03-31. It just seems like the data is shifted a number of quarters for some instruments.

[instruments_8_kpis_quarter_summary.txt](https://github.com/Borsdata-Sweden/API/files/6617810/instruments_8_kpis_quarter_summary.txt)

**Comment by Gillquist** [comment]
Hi, have not checked the specifics but recognize the discussion. Is this due to some companies report on different financial year. Ex if FY starts 1 April. Q4 ends 31 March year after. This is the case for Addtech (Id 8) FY21 ends 31 of March.

**Comment by henrikbergstrom** [comment]
Yes. Gillquist is correct.
Over 100 companies in Nordic has **Broken financial year**.
Looks strange - but is correct.

![image](https://user-images.githubusercontent.com/5638499/121253505-7b624c80-c8a9-11eb-8020-4c2df4b6c604.png)
https://borsdata.se/en/info/data/reportdata

In API Reportdata you have   "broken_Fiscal_Year": true to check this.

**Comment by ember91** [comment]
All right. Thanks!
