### ISSUE TITLE
API Dividend KPI errors

### ISSUE THREAD

**Issue by ember91** [Borsdata-Sweden/API#16]
Sometimes it seems like there are errors in the API data. For example, instrument 565 (QuiaPEG) Q2 2017 had a dividend (KPI 7) of 5.5 SEK. The stock price of that same instrument in the middle of 2017 was about 1.3 SEK.

Commonly a dividend yield of about 10 % of the stock price is considered high, but this is several hundred percent.

More examples:
* 1314 (Bosjö fastigheter) Q4 2020
* 1266 (NewCap Holding) Q2 2020 and Q4 2019
* 111 (Rolling Optics) Q4 2019 and Q4 2018

**Comment by henrikbergstrom** [comment]
Hi, Sorry late answer. This is correct.
Dividend normaly comes from last full year report.
Quarter report dont show Dividend.
Check 2016 report and you find 5.5 Dividend.
![image](https://user-images.githubusercontent.com/5638499/201609594-4b386781-fc11-402d-95c8-2c6e8bb2c2a9.png)

**Comment by ember91** [comment]
All right! Closing this.
