### ISSUE TITLE
Var hittar jag metoden för att komma åt KPIn?

### ISSUE THREAD

**Issue by Mintmi** [Borsdata-Sweden/API#18]
Hej,
Jag är nybörjare med detta och försökt hitta hur jag kommer åt KPIn i Python. 

Efter att ha initierat APIn försöker jag med följande rad få fram tillgängliga metoder:

"print(dir(borsdata))"

Som output får jag inte fram något som liknar KPI. Jag har försökt att hitta i dokumentationen, men inte hittat.

Fram tills jag kom till KPIn lyckades jag få fram diverse data. Jag undrar också om det finns  dokumentation för Börsdata SDK.

Mvh Esa

**Comment by Mintmi** [comment]
Hej igen,

En liten förklaring till ovanstående:

Jag skulle gärna fortsätta med att ta fram även KPI data direkt från APIn istället för den krångligare vägen via HTTP requests.

mvh Esa

**Comment by henrikbergstrom** [comment]
Hej,
Lite osäker men jag gissar att du vill få en lista med alla anrop på denna sidan?
https://github.com/Borsdata-Sweden/API/wiki/Kpi-Holdings-List
https://github.com/Borsdata-Sweden/API/wiki/KPI-History#kpi-table

Vi har inget anrop för detta utan du får själv lägga in den koden du vill använda.
Tänk på att det bli mycket anrop om du ska köra alla anrop.
https://github.com/Borsdata-Sweden/API/wiki#rate-limits

**Comment by Mintmi** [comment]
Hej,

Tack för ett snabbt svar. Ska kolla lite hur jag gör.

Mvh Esa
