### ISSUE TITLE
TypeError: "stockPriceCurrency"

### ISSUE THREAD

**Issue by andreasklippinge** [Borsdata-Sweden/API#19]
Hej, 

Jag märkte att min kod från igårkväll inte hade körts och testade igen med en mindre kodsnipp bara för att testa: 
```
from borsdata_sdk import BorsdataAPI
import pandas as pd

bd = BorsdataAPI("API")

instruments = bd.get_instruments()
```

Jag kan inte längre anropa `instruments = bd.get_instruments()` för då får jag följande felmeddelande: 
```
  File ~\AppData\Local\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\untitled0.py:6
    instruments = bd.get_instruments()

  File ~\AppData\Local\anaconda3\Lib\site-packages\borsdata_sdk\BorsdataAPI.py:130 in get_instruments
    instruments = [

  File ~\AppData\Local\anaconda3\Lib\site-packages\borsdata_sdk\BorsdataAPI.py:131 in <listcomp>
    Instrument(**instrument)

TypeError: Instrument.__init__() got an unexpected keyword argument 'stockPriceCurrency'
```

Är det någon uppdatering som har gjorts under natten? Min kod funkade felfritt fram tills igårkväll. 
Tack så länge!

**Comment by andreasklippinge** [comment]
Det verkar som att problemet var lätt löst, genom att anropa 
``` 
bd.get_instruments_updated()
```

**Comment by henrikbergstrom** [comment]
Hej,
Vi har lagt till två nya värden i Instruments,
https://borsdata.se/news/orginalrapportvaluta

Detta borde inte få koden att krascha men ert Python lib gör tyvärr det. 
Vi kan inte koda Python eller testa av detta. 3e-part lib. 
Du behöver lägga in dessa nya värden i instruments filen.
Sorry,

**Comment by henrikbergstrom** [comment]
AttributeError: 'InstrumentUpdate' object has no attribute 'ticker' ?
Detta är lite skumt för vi har aldrig get 'ticker' i detta anropet.

**Comment by andreasklippinge** [comment]
> Hej, Vi har lagt till två nya värden i Instruments, https://borsdata.se/news/orginalrapportvaluta
> 
> Detta borde inte få koden att krascha men ert Python lib gör tyvärr det. Vi kan inte koda Python eller testa av detta. 3e-part lib. Du behöver lägga in dessa nya värden i instruments filen. Sorry,

Tjena! 

Jag förstår helt, saken som gjorde mig frustrerad igår var informationen kring uppdateringen - när min kod kraschade så fanns det ingen info att läsa kring uppdateringen - den lades till senare under dagen. Eventuellt jag som var lite för het på gröten också, men i framtiden så hade jag uppskattat om det fanns info att läsa om en uppdatering eller liknande.
