### ISSUE TITLE
Discrepancy Between Published API Schema and Actual API Responses

### ISSUE THREAD

**Issue by linussvarm** [Borsdata-Sweden/API#22]
I have noticed that in your API schema (the one available at `https://apidoc.borsdata.se/swagger/v1/swagger.json`) you have changed the names of some properties/fields in certain models. For example, in the schema for the model KpiV1, the properties named `i`, `n`, and `s` have been replaced with `instrument_id`, `num_value`, and `string_value`. Other models have similar changes.

The problem is that your actual API endpoints generate responses according to the older definition. So right now, there is a discrepancy between the published schema and what is actually being used.

One issue caused by this is that clients auto-generated with Swagger are not functioning.
It is also impossible to use the schema to verify API responses. 

To avoid breaking implementations that consume you API:s, it might be a good idea to roll back the breaking changes to the schema.

**Comment by henrikbergstrom** [comment]
Thanks,
Docs swagger is now updated,
